---
title: "Study Lakes main calculations and paper figures"
author: "J Dawson"
date: '2021-03-31'
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Importing Data}
rm(list=ls())

library(naniar)
library(dplyr)
library(ggplot2)
library(readr)
library(reshape2)
library(emmeans)
library(cowplot)
library(multcomp)

#Github connection to dataset for CompleteIso with the BsM comparison lakes
data <- read_csv("../data/Dawson-Isotopes-StudyLakes.csv")
#Adding new lakes from Johnston
new_dat <- read_csv("../data/Dawson-Isotopes-2024Feb06.csv")
new_dat <- subset(new_dat, select=-c(FISH, REGION, YEAR, DAY, COMP, Tissue, Check, Comments)) %>%
          rename("SIASAM" = "SIA SAM",
               "Water" = "WBY",
               "d13C" = "Del 13C",
               "d15N" = "Del 15N",
               "C.N" = "C/N")
new_dat$Water[new_dat$Water == "Manitou-2"] <- "Manitou"
#df
cols.num <- c("d13C","d15N", "C.N", "FLEN", "TLEN", "RWT")
new_dat[cols.num] <- sapply(new_dat[cols.num],as.numeric)
data <- bind_rows(data, new_dat)
data<- data[!is.na(data$d13C),]

rm(new_dat)
```

```{r Cleaning data, creating variables}
#Subset for baselines
base_data <- data %>%
  filter(grepl("EPH|ZOOP|PERI|MAYFLY|EPHEMERI|SNAIL|CLAM|CRAYFISH|AMPHIPOD|HEPTAGEN", TAXON)) %>%
  mutate(TAXON = recode(TAXON, EPH='MAYFLY', EPHEMERI='MAYFLY', HEPTAGEN='MAYFLY'))

#mean d13C, d15N, sd by baseline
base_data <- base_data %>%
  group_by(Water, TAXON) %>%
  subset(TAXON %in% c("CLAM", "MAYFLY", "ZOOP","SNAIL","AMPHIPOD")) %>%
  summarise(mean_d13C = mean(d13C), mean_d15N = mean(d15N), sd_d13C = sd(d13C), sd_d15N = sd(d15N))

#df w columns for d13C, d15N by baseline
d13C <- dcast(data = base_data, formula = Water ~ TAXON, value.var = "mean_d13C")
d13C <- d13C %>% 
        rename("d13C_clam" = "CLAM",
               "d13C_eph" = "MAYFLY",
               "d13C_zoop" = "ZOOP",
               "d13C_snail" = "SNAIL",
               "d13C_amph" = "AMPHIPOD")

d15N <- dcast(data = base_data, formula = Water ~ TAXON, value.var = "mean_d15N")
d15N <- d15N %>% 
        rename("d15N_clam" = "CLAM",
               "d15N_eph" = "MAYFLY",
               "d15N_zoop" = "ZOOP",
               "d15N_snail" = "SNAIL",
               "d15N_amph" = "AMPHIPOD")

base_data <- merge(d13C, d15N, by = "Water")

###Some ref lakes do not have zoop baseline, so combine Zoop and Clam column for it (pel)
base_data$d13C_pel <- coalesce(base_data$d13C_clam,base_data$d13C_zoop)
base_data$d15N_pel <- coalesce(base_data$d15N_clam,base_data$d15N_zoop)
base_data$d13C_lit <- coalesce(base_data$d13C_eph,base_data$d13C_snail)
base_data$d15N_lit <- coalesce(base_data$d15N_eph,base_data$d15N_snail)

base_data <- subset(base_data, select=c(Water, d13C_pel, d15N_pel, d13C_lit, d15N_lit))
data<-left_join(data,base_data,keep=F)
rm(d13C, d15N, base_data)

##Remove baseline entries
data <- data %>%
  filter(!grepl("EPH|ZOOP|PERI|MAYFLY|HEPTAGEN|EPHEMERI|CRAYFISH|CLAM|SNAIL|AMPHIPOD", TAXON))

##standardizing length
LEN <- subset(data, select=c(Water,TAXON,FLEN,TLEN)) %>%
  na.omit()
LEN <- LEN %>%
  group_by(TAXON) %>%
  summarize(x_TLEN = mean(TLEN), x_FLEN = mean(FLEN))
LEN$x_diff <- LEN$x_TLEN - LEN$x_FLEN

data<-left_join(data,LEN,keep=F)
data$length <- (data$FLEN+data$x_diff)
data$length <- coalesce(data$TLEN,data$length)
data$length <- coalesce(data$length,data$FLEN)

LEN_sum<- data %>%
  group_by(Water, TAXON) %>%
  summarise(length_mean = mean(length, na.rm=T), length_sd = sd(length, na.rm=T))
data <- merge(data, LEN_sum, by = c("Water", "TAXON"))
data  <- subset(data, select=-c(TLEN, FLEN, x_TLEN, x_FLEN, x_diff))

#mean C, N w/ sd
SI<- data%>%
  group_by(Water, TAXON) %>%
  summarise(d13C_mean = mean(d13C), d13C_sd = sd(d13C), d13C_max = max(d13C), d13C_min = min(d13C), d15N_mean = mean(d15N), d15N_sd = sd(d15N), d15N_max = max(d15N), d15N_min = min(d15N))
SI$d13Crange <- SI$d13C_max-SI$d13C_min
SI$d15Nrange <- SI$d15N_max-SI$d15N_min
  
data <- data %>%
  mutate(Water2 = case_when(
    Water %in% c("Stormy", "Mendelssohn", "Manitou", "Turtleshell", "Wawiashkashi") ~ "Reference",
    TRUE ~ Water
  ))
data <- data %>%
    mutate(Water2 = recode(Water2, 'Baby Lk.'='Barren Lake', 'Daisy Lk.'='Semi-barren Lake', 'Nelson Lk.'='Forested Lake'))

#adding nice label group
data$Water2[data$Water2 == "Baby Lk."]<-"Barren Lake"
data$Water2[data$Water2 == "Daisy Lk."]<-"Semi-barren Lake"
data$Water2[data$Water2 == "Nelson Lk."]<-"Forested Lake"
data$Lake <- NA
data$Lake = data$Water
data$Lake[data$Lake == "Baby Lk."]<-"Barren Lake"
data$Lake[data$Lake == "Daisy Lk."]<-"Semi-barren Lake"
data$Lake[data$Lake == "Nelson Lk."]<-"Forested Lake"
data$Lake[data$Lake == "Mendelssohn"]<-"Reference 1"
data$Lake[data$Lake == "Turtleshell"]<-"Reference 2"
data$Lake[data$Lake == "Manitou"]<-"Reference 3"
data$Lake[data$Lake == "Wawiashkashi"]<-"Reference 4"
data$Lake[data$Lake == "Stormy"]<-"Reference 5"

rm(LEN, LEN_sum)
```

```{r Proportion Littoral calculation}
#lipid correction d13C
data$d13C_norm <- data$d13C + (-3.32 + (0.99*data$C.N))
#prop lit
data$p_lit <- (data$d13C_norm - data$d13C_pel)/(data$d13C_lit - data$d13C_pel)
#plotting
hist(subset(data$p_lit, data$TAXON %in% c("SMB","YPERCH")))

smbyp_CN<-ggplot(subset(data, TAXON %in% c("SMB", "YPERCH")), aes(x = d13C_norm, y = d15N, colour = TAXON, group = TAXON)) +
  geom_point(show.legend = FALSE) +
  facet_wrap(~factor(Lake, c("Barren Lake", "Semi-barren Lake", "Forested Lake", "Reference 1", "Reference 2", "Reference 3", "Reference 4", "Reference 5")))
smbyp_CN + geom_point(aes(x = d13C_lit, y = d15N_lit, colour = "littoral")) +
  geom_point(aes(x = d13C_pel, y = d15N_pel, colour = "pelagic"))

#adjusted (<0 and 100<)
data$adjp_lit <- NA
data$adjp_lit = data$p_lit
data$adjp_lit[data$p_lit>1] <- 1.00
data$adjp_lit[data$p_lit<0] <- 0.00
hist(subset(data$adjp_lit, data$TAXON %in% c("SMB", "YPERCH")))

rm(smbyp_CN)

data$plit_bound <- NA
data$plit_bound = data$p_lit
data$plit_bound[data$p_lit>1.5] <- NA
data$plit_bound[data$p_lit<(-0.5)] <- NA

pn<-data %>%
  group_by(Water) %>%
  filter(!is.na(plit_bound)) %>%
  mutate(pl_n = ((plit_bound - min(plit_bound))/(max(plit_bound) - min(plit_bound)))
         ) %>%
  subset(select = c("SIASAM", "pl_n"))

data<- full_join(data,pn, by="SIASAM")

data %>%
  group_by(Water2, TAXON) %>%
  summarise(n= n())

#summarize pl by water + taxon-- Using prop lit that's been lipid corrected and removed outliers, adjpl is lipid corrected and bound between 0-1
data_sum <- data %>% group_by(Water, TAXON) %>%
  summarise(mean.pl = mean(plit_bound), sd.pl = sd(plit_bound), mean.adjpl = mean(adjp_lit), sd.adjpl = sd(adjp_lit))
#add to df
data <- merge(data, data_sum, by = c("Water", "TAXON"))

#calculate proportion of data outside of 0-1 PL raw values
pl_in <- data %>%
  filter(!p_lit > 1.01) %>%
  filter(!p_lit < (0)) %>%
  filter(TAXON == c('SMB','YPERCH'))
pl_over <- data %>%
  filter(!p_lit < 1.01) %>%
  filter(TAXON == c('SMB','YPERCH'))
pl_under <- data %>%
  filter(!p_lit > (0))%>%
  filter(TAXON == c('YPERCH'))

num_in<- pl_in %>%
  summarise(n= n())
num_over <- pl_over %>%
  summarise(n= n())
num_under <- pl_under %>%
  summarise(n= n())
num_out <- num_under + num_over
proportion_in <- ((num_in)/(num_in + num_out))*100
proportion_in

rm(data_sum, pn, pl_in, pl_over, pl_under, num_in, num_over, num_under, num_out)
```

```{r Trophic Position calculation}
# two baseline
data$tp_2 <- 2 + ((data$d15N - ((data$d15N_pel*(1 - data$adjp_lit)) + (data$d15N_lit*data$adjp_lit)))/3.4)

#summarize tp by water + taxon
data_sum_tp <- data %>% group_by(Water, TAXON) %>%
  summarise(mean.tp2 = mean(tp_2), sd.tp2 = sd(tp_2))
#add to df
data <- merge(data, data_sum_tp, by = c("Water", "TAXON"))

rm(data_sum_tp)
```

```{r ANOVA/ANCOVA proportion littoral and TP w/ length}
#######################
###  PROP LITTORAL  ###
#######################
data$TAXON <- as.factor(data$TAXON)
#path_out <- "../data/"
#write.csv(data,paste(path_out,'ellipse-data_Mar04.csv',sep = ''))

#######
# SMB #
#######
#ANOVA
smb_pl_mod<- lm(adjp_lit~Water, data=data, subset=(TAXON=="SMB"))
anova(smb_pl_mod)
#contrasts
smb_pl_em<-emmeans(smb_pl_mod, pairwise ~ Water, adjust = "none")
smb_pl_em
#letters
#mod_means <- cld(smb_pl_em, alpha = 0.05, Letters = letters)
#df
x<-as.data.frame(summary(smb_pl_em)$emmeans)
x <- x %>%
  mutate(Water2 = case_when(
    Water %in% c("Stormy", "Mendelssohn", "Manitou", "Turtleshell", "Wawiashkashi") ~ "Reference",
    TRUE ~ Water
  )) %>%
  group_by(Water2) %>%
  summarise(gemmean = mean(emmean), glower.CL = mean(lower.CL), gupper.CL = mean(upper.CL))
x$TAXON<-"SMB"
x<-as.data.frame(x)

#x<-merge(x,mod_means)
#x$.group<-gsub("[[:space:]]", "", x$.group)
#x <- merge(x, ls)
#plot
SMB_PL_length<-ggplot(x, aes(x=Water2, y=gemmean))+
  geom_errorbar(aes(ymin=glower.CL, ymax=gupper.CL), width=0.2)+
  geom_point() +
  ylim(-0.1,1.2) +
  ylab("SMB Proportion Littoral") + 
  theme_bw()

##YP
#ANOVA 
yp_pl_mod<- lm(adjp_lit~Water+length, data=data, subset=(TAXON=="YPERCH"))
anova(yp_pl_mod)
#ANCOVA w/ length interaction + contrasts
yp_pl_em<-emmeans(yp_pl_mod, pairwise ~ Water, adjust = "none")
yp_pl_em
#grand mean
x1<-as.data.frame(summary(yp_pl_em)$emmeans)
x1 <- x1 %>%
  mutate(Water2 = case_when(
    Water %in% c("Stormy", "Mendelssohn", "Manitou", "Turtleshell", "Wawiashkashi") ~ "Reference",
    TRUE ~ Water
  )) %>%
  group_by(Water2) %>%
  summarise(gemmean = mean(emmean), glower.CL = mean(lower.CL), gupper.CL = mean(upper.CL))
x1$TAXON <- "YPERCH"
x1<-as.data.frame(x1)

#plot
YP_PL_length<-ggplot(x1, aes(x=Water2, y=gemmean))+
  geom_errorbar(aes(ymin=glower.CL, ymax=gupper.CL), width=0.2)+
  geom_point()+
  ylim(-0.1,1.2) +
  ylab("YP Proportion Littoral") +  
  theme_bw()
#stitch together PL plot df
PL_gm <- full_join(x,x1)
PL_gm$letter <- c("A", "A", "B", "C", "AC", "BC", "A", "C")
#plot
lakelab <- c("Barren Lake", "Semi-barren Lake", "Forested Lake", "Reference Lakes")
PL<-ggplot(PL_gm, aes(x=Water2, y=gemmean, colour=TAXON))+
  geom_errorbar(aes(ymin=glower.CL, ymax=gupper.CL), width=0.4, size = 1, position = position_dodge(0.5),show.legend=F)+
  geom_point(size = 3, position = position_dodge(0.5))+
  geom_text(aes(x = Water2, y = gupper.CL,label = letter, group = TAXON), 
            position = position_dodge(width = 0.5), vjust = -0.5, colour = "black", size =5) +
  ylim(0,1.2) +
  ylab("Proportion Littoral") + 
  scale_colour_manual(labels = c("Smallmouth bass", "Yellow perch"), values = c("#D8B365", "#5AB4AC"), guide="none") +
  theme_bw()+
  theme(axis.title.x = element_blank())+
  scale_x_discrete(labels = lakelab)


#####################
###      TP       ###
#####################

##SMB
#ANOVA
smb_tp_mod<- lm(tp_2~Water+length, data=data, subset=(TAXON=="SMB"))
anova(smb_tp_mod)
#ANCOVA
smb_tp<-emmeans(smb_tp_mod, pairwise ~ Water, adjust = "none")
smb_tp
#grand mean
x2<-as.data.frame(summary(smb_tp)$emmeans)
x2 <- x2 %>%
  mutate(Water2 = case_when(
    Water %in% c("Stormy", "Mendelssohn", "Manitou", "Turtleshell", "Wawiashkashi") ~ "Reference",
    TRUE ~ Water
  )) %>%
  group_by(Water2) %>%
  summarise(gemmean = mean(emmean), glower.CL = mean(lower.CL), gupper.CL = mean(upper.CL))
x2$TAXON<-"SMB"
x2<-as.data.frame(x2)
#plot
SMB_TP_size<-ggplot(x2, aes(x=Water2, y=gemmean))+
  geom_errorbar(aes(ymin=glower.CL, ymax=gupper.CL), width=0.2)+
  geom_point()+
  ylim(2.9,4.25) +
  ylab("SMB Trophic Position") + 
  theme_bw()

##YP
yp_tp_mod<- lm(tp_2~Water+length, data=data, subset=(TAXON=="YPERCH"))
anova(yp_tp_mod)
#contrasts
yp_tp<-emmeans(yp_tp_mod, pairwise ~ Water, adjust = "none")
yp_tp
#grand mean
x3<-as.data.frame(summary(yp_tp)$emmeans)
x3 <- x3 %>%
  mutate(Water2 = case_when(
    Water %in% c("Stormy", "Mendelssohn", "Manitou", "Turtleshell", "Wawiashkashi") ~ "Reference",
    TRUE ~ Water
  )) %>%
  group_by(Water2) %>%
  summarise(gemmean = mean(emmean), glower.CL = mean(lower.CL), gupper.CL = mean(upper.CL))
x3$TAXON<-"YPERCH"
x3<-as.data.frame(x3)

#plot
YP_TP_size<-ggplot(x3, aes(x=Water2, y=gemmean))+
  geom_errorbar(aes(ymin=glower.CL, ymax=gupper.CL), width=0.2)+
  geom_point()+
  ylim(2.9,4.25) +
  ylab("YP Trophic Position") +
  theme_bw()
#stitch df
TP_gm<-full_join(x2,x3)
TP_gm$letter <- c("A", "B", "B", "B", "A", "A", "A", "A")
#plot
TP<- ggplot(TP_gm, aes(x=Water2, y=gemmean, colour=TAXON))+
  geom_errorbar(aes(ymin=glower.CL, ymax=gupper.CL), width=0.4, size = 1, position = position_dodge(0.5),show.legend=F)+
  geom_point(position = position_dodge(0.5), size = 3)+
  geom_text(aes(x = Water2, y = gupper.CL,label = letter, group = TAXON), 
            position = position_dodge(width = 0.5), vjust = -0.5, colour = "black", size =5) +
  ylim(2.9,4.1)+
  ylab("Trophic Position")+
  scale_colour_manual(name = "Species", labels = c("Smallmouth bass", "Yellow perch"), values = c("#D8B365", "#5AB4AC")) +
  theme_bw()+
  theme(axis.title.x = element_blank()) +
  scale_x_discrete(labels = lakelab)

legend<- get_legend(TP +
                      guides(colour = guide_legend(nrow=1)) +
                      theme(legend.position = "bottom"))

##final plot
pl2<-plot_grid(PL + theme(legend.position="none"), 
          TP + theme(legend.position="none"), 
          labels = "AUTO")
plot_grid(pl2, legend, ncol=1, rel_heights = c(1, .1))

rm(smb_pl_mod, yp_pl_mod, smb_tp_mod, yp_tp_mod, x, x1, x2, x3)
```

```{r SEA Ellipse plot - CJFAS Fig 3 Isoscape plot}
sea<-data %>%
  subset(select = c("Water","Water2","Lake", "TAXON", "p_lit", "adjp_lit","plit_bound", "tp_2")) %>%
  filter(TAXON %in% c("SMB", "YPERCH"))

#hist(sea$p_lit)

#40% ellipse with PL (-0.5-1.5, lipid corr)
ggplot(sea, aes(x = plit_bound, y = tp_2, colour = TAXON, group = interaction(Lake, TAXON))) +
  stat_ellipse(type = "norm", level = 0.4, lwd = 1.5) +
  theme_classic(base_size = 14) +
  ylab("Trophic Position")+
  xlab("Proportion Littoral")+
  scale_colour_manual(name = "Species", labels = c("Smallmouth bass", "Yellow perch"), values = c("#D8B365", "#5AB4AC"))+
  theme(legend.position = "bottom")+
  facet_wrap(~factor(Lake, c("Barren Lake", "Semi-barren Lake", "Forested Lake", "Reference 1", "Reference 2", "Reference 3", "Reference 4", "Reference 5")))

  zz<- stat_ellipse(data = sea, aes(x = plit_bound, y = tp_2, colour = TAXON, group = interaction(Water, TAXON), type = "norm", level = 0.4, lwd = 1.5)) 
str(zz)
zz$compute_geom_1

#40% adjusted plit
ggplot(sea, aes(x = adjp_lit, y = tp_2, colour = TAXON, group = interaction(Lake, TAXON))) +
  stat_ellipse(type = "norm", level = 0.4, lwd = 1.5) +
  theme_classic(base_size = 14) +
  labs(title = "Adj PL 40% ellipse") +
  scale_colour_manual(name = "Species", labels = c("Smallmouth bass", "Yellow perch"), values = c("#D8B365", "#5AB4AC"))+
    theme(legend.position = "bottom")+
  facet_wrap(~factor(Lake, c("Barren Lake", "Semi-barren Lake", "Forested Lake", "Reference 1", "Reference 2", "Reference 3", "Reference 4", "Reference 5")))

#path_out <- "../data/"
#write.csv(sea,paste(path_out,'big-siberdat.csv',sep = ''))
```

SUPPLEMENTAL FIGURES

```{r PL, TP plotting reference lakes individually - Supplemental}
#pl
smb_pl_ref<-as.data.frame(summary(smb_pl_em)$emmeans)%>%
  filter(!Water %in% c("Baby Lk.", "Daisy Lk.", "Nelson Lk."))
smb_pl_ref$TAXON<-"SMB"
smb_pl_ref<-as.data.frame(smb_pl_ref)
yp_pl_ref<-as.data.frame(summary(yp_pl_em)$emmeans)%>%
  filter(!Water %in% c("Baby Lk.", "Daisy Lk.", "Nelson Lk."))
yp_pl_ref$TAXON<-"YPERCH"
yp_pl_ref<-as.data.frame(yp_pl_ref)
pl_ref<- full_join(smb_pl_ref, yp_pl_ref)
pl_ref$Lake<-NA
pl_ref$Lake[pl_ref$Water == "Mendelssohn"]<-"Reference 1"
pl_ref$Lake[pl_ref$Water == "Turtleshell"]<-"Reference 2"
pl_ref$Lake[pl_ref$Water == "Manitou"]<-"Reference 3"
pl_ref$Lake[pl_ref$Water == "Wawiashkashi"]<-"Reference 4"
pl_ref$Lake[pl_ref$Water == "Stormy"]<-"Reference 5"
pl_ref$letter <- c("A", "A", "B", "B", "A", "B", "A", "C", "BC", "AB")

refPL<-ggplot(pl_ref, aes(x=Lake, y=emmean, colour=TAXON))+
  geom_errorbar(aes(ymin=lower.CL, ymax=upper.CL), width=0.4, size = 1, position = position_dodge(0.5),show.legend=F)+
  geom_point(position = position_dodge(0.5), size = 3)+
  geom_text(aes(x = Lake, y = upper.CL,label = letter, group = TAXON), 
            position = position_dodge(width = 0.5), vjust = -0.5, colour = "black", size =5) +
  ylim(-0.1,1.0)+
  ylab("Proportion Littoral")+
  scale_colour_manual(name = "Species", labels = c("Smallmouth bass", "Yellow perch"), values = c("#D8B365", "#5AB4AC")) +
  theme_bw()+
  theme(axis.title.x = element_blank()) +
  scale_x_discrete()

#tp
smb_tp_ref<-as.data.frame(summary(smb_tp)$emmeans) %>%
  filter(!Water %in% c("Baby Lk.", "Daisy Lk.", "Nelson Lk."))
smb_tp_ref$TAXON<-"SMB"
smb_tp_ref<-as.data.frame(smb_tp_ref)
yp_tp_ref<-as.data.frame(summary(yp_tp)$emmeans)%>%
  filter(!Water %in% c("Baby Lk.", "Daisy Lk.", "Nelson Lk."))
yp_tp_ref$TAXON<-"YPERCH"
yp_tp_ref<-as.data.frame(yp_tp_ref)
tp_ref<- full_join(smb_tp_ref, yp_tp_ref)
tp_ref$Lake<-NA
tp_ref$Lake[tp_ref$Water == "Mendelssohn"]<-"Reference 1"
tp_ref$Lake[tp_ref$Water == "Turtleshell"]<-"Reference 2"
tp_ref$Lake[tp_ref$Water == "Manitou"]<-"Reference 3"
tp_ref$Lake[tp_ref$Water == "Wawiashkashi"]<-"Reference 4"
tp_ref$Lake[tp_ref$Water == "Stormy"]<-"Reference 5"
tp_ref$letter <- c("B", "A", "B", "BC", "C", "A", "A", "A", "A", "A")

refTP<-ggplot(tp_ref, aes(x=Lake, y=emmean, colour=TAXON))+
  geom_errorbar(aes(ymin=lower.CL, ymax=upper.CL), width=0.4, size = 1, position = position_dodge(0.5),show.legend=F)+
  geom_point(position = position_dodge(0.5), size = 3)+
    geom_text(aes(x = Lake, y = upper.CL,label = letter, group = TAXON), 
            position = position_dodge(width = 0.5), vjust = -0.5, colour = "black", size =5) +
  ylim(3.0,4.4)+
  ylab("Trophic Position")+
  scale_colour_manual(name = "Species", labels = c("Smallmouth bass", "Yellow perch"), values = c("#D8B365", "#5AB4AC")) +
  theme_bw()+
  theme(axis.title.x = element_blank()) +
  scale_x_discrete()

legend<- get_legend(refTP +
                      guides(colour = guide_legend(nrow=1)) +
                      theme(legend.position = "bottom"))

##2 panel plot
tt<-plot_grid(refPL + theme(legend.position="none"), 
          refTP + theme(legend.position="none"), 
          labels = "AUTO")

plot_grid(tt, legend, ncol=1, rel_heights = c(1, .1))

#rm(smb_pl_em, yp_pl_em, smb_pl_ref, yp_pl_ref, smb_tp, yp_tp, smb_tp_ref, yp_tp_ref)
```

```{r S15 - C:N Ratio (A), Fultons Index (B)}
##C:N MEAN
#df
cond_dat <- data %>%
  group_by(Lake, TAXON) %>%
  filter(TAXON %in% c("SMB", "YPERCH")) %>%
  summarise(mean.CN = mean(C.N), sd.CN = sd(C.N), mean.length = mean(length), sd.length = sd(length), mean.rwt = mean(RWT), sd.rwt = sd(RWT))

ref_cond_dat <- cond_dat %>%
  filter(Lake %in% c("Reference 1", "Reference 2", "Reference 3", "Reference 4", "Reference 5")) %>%
  group_by(TAXON) %>%
  summarise(mean.CN = mean(mean.CN), sd.CN = mean(sd.CN))
ref_cond_dat$Lake <- "Reference Lakes"
cond_dat <- rbind(cond_dat, ref_cond_dat)

#plot
CNplot<-ggplot(subset(cond_dat, Lake %in% c("Barren Lake", "Semi-barren Lake", "Forested Lake", "Reference Lakes")), aes(x=Lake, y=mean.CN, colour=TAXON))+
  geom_errorbar(aes(ymin=(mean.CN-sd.CN), ymax=(mean.CN+sd.CN)), width=0.4, size = 1, position = position_dodge(0.5),show.legend=F)+
  geom_point(position = position_dodge(0.5), size = 3)+
  ylab("Mean C:N Ratio +/- sd")+
  scale_colour_manual(name = "Species", labels = c("Smallmouth bass", "Yellow perch"), values = c("#D8B365", "#5AB4AC")) +
  theme_bw()+
  theme(axis.title.x = element_blank()) +
  scale_x_discrete(labels = lakelab)

#C:N ANOVA
CN_YP<-data %>%
  subset(select = c("Water2","Lake", "TAXON", "C.N")) %>%
  filter(TAXON %in% c("YPERCH"))
CN_SMB<-data %>%
  subset(select = c("Water2","Lake", "TAXON", "C.N")) %>%
  filter(TAXON %in% c("SMB"))

yp_cn_aov<-aov(C.N ~ Water2, data = CN_YP)
summary(yp_cn_aov)
smb_cn_aov<-aov(C.N ~ Water2, data = CN_SMB)
summary(smb_cn_aov)
TukeyHSD(smb_cn_aov, which = "Water2")

##FI
#add FI to 'data'
data$FI <- NA
data$FI <- (data$RWT/(data$length^3)) * 100000
FIdat <- data[!is.na(data$FI),]
FIdat <- data %>%
  filter(TAXON %in% c("SMB", "YPERCH")) %>%
  group_by(Lake, TAXON) %>%
  summarise(mean.FI = mean(FI), sd.FI = sd(FI))

ref_FIdat <- FIdat %>%
  filter(Lake %in% c("Reference 1", "Reference 2", "Reference 3", "Reference 4", "Reference 5")) %>%
  group_by(TAXON) %>%
  summarise(mean.FI = mean(mean.FI, na.rm=T), sd.FI = mean(sd.FI, na.rm=T))
ref_FIdat$Lake <- "Reference Lakes"
FIdat <- rbind(FIdat, ref_FIdat)

#plot
FIplot<-ggplot(subset(FIdat, Lake %in% c("Barren Lake", "Semi-barren Lake", "Forested Lake", "Reference Lakes")), aes(x=Lake, y=mean.FI, colour=TAXON))+
  geom_errorbar(aes(ymin=(mean.FI-sd.FI), ymax=(mean.FI+sd.FI)), width=0.4, size = 1, position = position_dodge(0.5),show.legend=F)+
  geom_point(position = position_dodge(0.5), size = 3)+
  ylab("Mean Fulton's Index +/- sd")+
  scale_colour_manual(name = "Species", labels = c("Smallmouth bass", "Yellow perch"), values = c("#D8B365", "#5AB4AC")) +
  theme_bw()+
  theme(axis.title.x = element_blank()) +
  scale_x_discrete(labels = lakelab)

#anova
FI_YP<-data %>%
  subset(select = c("Water2","Lake", "TAXON", "FI")) %>%
  filter(TAXON %in% c("YPERCH"))
FI_SMB<-data %>%
  subset(select = c("Water2","Lake", "TAXON", "FI")) %>%
  filter(TAXON %in% c("SMB"))

yp_fi_aov<-aov(FI ~ Water2, data = FI_YP)
summary(yp_fi_aov)
TukeyHSD(yp_fi_aov, which = "Water2")
smb_fi_aov<-aov(FI ~ Water2, data = FI_SMB)
summary(smb_fi_aov)
TukeyHSD(smb_fi_aov, which = "Water2")

#FIdat$letter <- c("B", "A", "B", "BC", "C", "A", "A", "A", "A", "A")

cond_2p<-plot_grid(CNplot + theme(legend.position="none"), 
          FIplot + theme(legend.position="none"), 
          labels = "AUTO")
plot_grid(cond_2p, legend, ncol=1, rel_heights = c(1, .1))

rm(ref_cond_dat, ref_FIdat)
```

```{r S14 - Adj vs Unadj Prop Littoral}
plit_dat<-data %>%
  subset(select = c(Water2, Lake, TAXON, p_lit, adjp_lit)) %>%
  filter(TAXON %in% c("SMB", "YPERCH")) %>%
  group_by(Water2, TAXON) %>%
  summarise(mean.plit = mean(p_lit), sd.plit = sd(p_lit), mean.adjpl = mean(adjp_lit), sd.adjpl = sd(adjp_lit))

#plot
unadjpl<-ggplot(plit_dat, aes(x=Water2, y=mean.plit, colour=TAXON))+
  geom_errorbar(aes(ymin=mean.plit-sd.plit, ymax=mean.plit+sd.plit), width=0.4, size = 1, position = position_dodge(0.5),show.legend=F)+
  geom_point(size = 3, position = position_dodge(0.5))+
  ylab("Mean Proportion Littoral (raw) +/- sd") + 
  scale_colour_manual(labels = c("Smallmouth bass", "Yellow perch"), values = c("#D8B365", "#5AB4AC"), guide="none") +
  theme_bw()+
  theme(axis.title.x = element_blank())+
  scale_x_discrete(labels = lakelab)

adjpl<-ggplot(plit_dat, aes(x=Water2, y=mean.adjpl, colour=TAXON))+
  geom_errorbar(aes(ymin=mean.adjpl-sd.adjpl, ymax=mean.adjpl+sd.adjpl), width=0.4, size = 1, position = position_dodge(0.5),show.legend=F)+
  geom_point(size = 3, position = position_dodge(0.5))+
  ylab("Mean Proportion Littoral (adjusted) +/- sd") + 
  scale_colour_manual(labels = c("Smallmouth bass", "Yellow perch"), values = c("#D8B365", "#5AB4AC"), guide="none") +
  theme_bw()+
  theme(axis.title.x = element_blank())+
  scale_x_discrete(labels = lakelab)

pl_2p<-plot_grid(unadjpl + theme(legend.position="none"), 
          adjpl + theme(legend.position="none"), 
          labels = "AUTO")
plot_grid(pl_2p, legend, ncol=1, rel_heights = c(1, .1))
```