---
title: "Watershed Lecture Presentation Plots"
author: "J Dawson"
date: '2020-10-23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Importing Data}
setwd("~/Desktop/Data/Working-Data")

library(naniar)

list.files()
data <- read.csv("Isotope_data_WORKING.csv")
isotope <- data[c(3,4,6,9,18,19,22)]
isotope$TAXON[isotope$TAXON == "131"] <- "NPIKE"
isotope$TAXON[isotope$TAXON == "163"] <- "WS"
isotope$TAXON[isotope$TAXON == "316"] <- "SMB"
isotope$TAXON[isotope$TAXON == "334"] <- "WALL"
isotope$TAXON[isotope$TAXON == "198"] <- "COSHIN"
isotope$TAXON[isotope$TAXON == "212"] <- "CCHUB"
isotope$TAXON[isotope$TAXON == "313"] <- "PSEED"
isotope$TAXON[isotope$TAXON == "331"] <- "YPERCH"
isotope$TAXON[isotope$TAXON == "233"] <- "BBULL"
isotope$TAXON[isotope$TAXON == "271"] <- "BUR"
isotope$TAXON[isotope$TAXON == "Ephemeroptera"] <- "EPH"
isotope$TAXON[isotope$TAXON == "Zooplankton"] <- "ZOOP"
isotope$TAXON[isotope$TAXON == "Periphyton"] <- "PERI"

##Tidying data from Tom
data2 <- read.csv("Dawson-Isotopes-2020Oct23.csv")
NL_Tomdat <- data2[c(1,3,7,14:16)] %>%
  replace_with_na_all(condition = ~.x == ".")%>%
  na.omit(data2)

NL_predfishiso<-NL_Tomdat %>% 
  rename(
    SIASAM = SIA.SAM,
    Water = WBY,
    X15N = Del.15N,
    d13C = Del.13C
    )

NL_predfishiso$Water[NL_predfishiso$Water == "Nelson"] <- "Nelson Lk."
NL_predfishiso$Site <- NA

```

```{r Subsetting Data}
##Subsetting isotope data by lake
BB_iso <- subset(isotope, isotope$Water == "Baby Lk.")
DY_iso <- subset(isotope, isotope$Water == "Daisy Lk.")

NL_iso <- subset(isotope, isotope$Water == "Nelson Lk.")
NL_iso <- rbind(NL_iso, NL_predfishiso)

##Subsetting isotope data by trophic grouping
###Predator fish subsetting
BB_DY_predfishiso <- subset(isotope, isotope$SIASAM<11000) 
NL_predfishiso
###Compiling predator fish data
predfishiso <- rbind(BB_DY_predfishiso, NL_predfishiso)

###Subsetting predator fish data by lake
bb_prediso <- subset(predfishiso, predfishiso$Water == "Baby Lk.")
dy_prediso <- subset(predfishiso, predfishiso$Water == "Daisy Lk.")
nl_prediso <- subset(predfishiso, predfishiso$Water == "Nelson Lk.")

###Compiling prey fish data
NL_preyfishiso <-subset(NL_fishiso, NL_fishiso$SIASAM>21800)
subset1 <- subset(isotope, isotope$SIASAM>11000)
subset2 <- subset(subset1, subset1$SIASAM<12000)

preyfishiso <- rbind(NL_predfishiso, subset2)

###Subsetting prey fish data by lake
bb_preyiso <- subset(preyfishiso, preyfishiso$Water == "Baby Lk.")
dy_preyiso <- subset(preyfishiso, preyfishiso$Water == "Daisy Lk.")
nl_preyiso <- subset(preyfishiso, preyfishiso$Water == "Nelson Lk.")
  
###Subsetting for baseline data
baseiso1 <- subset(isotope, isotope$SIASAM>12000)
baseiso <- subset(baseiso1, baseiso1$SIASAM<15000)

###Subsetting baseline data for baseline types
ephiso <- subset(baseiso, baseiso$TAXON == "EPH")

zoopiso <- subset(baseiso, baseiso$TAXON == "ZOOP")
  
periiso <- subset(baseiso, baseiso$TAXON == "PERI")

###Subsetting periphyton iso by lake
bb_peri <- subset(periiso, periiso$Water == "Baby Lk.")
dy_peri <- subset(periiso, periiso$Water == "Daisy Lk.")
nl_peri <- subset(periiso, periiso$Water == "Nelson Lk.")

``` 

##Dataset legend
__All lakes__
`isotope` is the whole dataset for isotope data
`predfishiso` is the complete predator fish (FLEN>=200mm) dataset
`preyfishiso` is the complete prey fish (FLEN<200mm) dataset
`baseiso` is the complete baseline isotope dataset
`ephiso`, `zoopiso`, and `periiso` are the isotope datasets for each type of baseline organism

__Lake-specific__
`BB_iso`, `DY_iso`, and `NL_iso` are the isotope datasets for each lake
`bb_prediso`, `dy_prediso`, and `nl_prediso` are the predator fish (FLEN>=200mm) isotopes for each lake
`bb_preyiso`, `dy_preyiso`, and `nl_preyiso` are the prey fish (FLEN<200mm) isotopes for each lake
`bb_peri`, `dy_peri`, and `nl_peri` are the periphyton isotope datasets for each lake

```{r let's make some plotsssss}
library(ggplot2)
#Total plot
ggplot(isotope, aes(d13C, X15N, colour = TAXON)) +
  geom_point(aes(shape = Water)) +
    labs(title="Relative abundance of 13C and 15N for all taxa and lakes", x="d13C", y="d15N")

##Baby Lake isotope plot
ggplot(BB_iso, aes(d13C, X15N, colour = TAXON)) +
  geom_point() +
  labs(title = "Baby Lake Isotope Data", x = "d13C", y = "d15N")

##Daisy Lake isotope plot
ggplot(DY_iso, aes(d13C, X15N, colour = TAXON)) +
  geom_point() +
  labs(title = "Daisy Lake Isotope Data", x = "d13C", y = "d15N")

##Nelson Lake isotope plot
ggplot(NL_iso, aes(d13C, X15N, colour = TAXON)) +
  geom_point() +
  labs(title = "Nelson Lake Isotope Data", x = "d13C", y = "d15N")
```